### ISSUE TITLE
Add additional github stuff

### ISSUE THREAD

**Issue by ezisazis** [sinisterstuf/GuessTheAnimal#12]
As the following stuff:
- [x] License to README
- [ ] PULL_REQUEST_TEMPLATE.MD
- [ ] CONTRIBUTING.MD
- [ ] CODE_OF_CONDUCT.md.
- [ ] Contributors list
- [x] https://www.codetriage.com badge (or any fancy badge)

... and so on

**Comment by sionleroux** [comment]
OK, did the first one already, added a short mention of the license in the README and linked it to the LICENSE.txt file.

**Comment by sionleroux** [comment]
I added a badge to the README to show the current status of [the last Travis CI build on the master branch](https://travis-ci.org/sinisterstuf/GuessTheAnimal) in 0cc14f7fca72245b19eb324abaec524720d4fc1a so that solves the "fancy badge" part. :wink:
